  mutation Login($input: LoginInput!) {
    Login(input: $input) {
      _id
      token
      email
      roles
      profile {
        first_name
        last_name
      }
    }
  }


    mutation Register($input: RegisterInput) {
    Register(input: $input) {
      _id
      token
    }
  }