  query SearchProducts ($input: SearchProductInput!) {
    SearchProducts(input: $input) {
      products{
      name
      _id
      }
      total
    }
  }

  query GetMappingAlias ($product:ID!, $retailer:ID){
    GetMappingAlias(product: $product, retailer: $retailer){
      total
    }
  }

  mutation CreateAliasByManager($input: MappingAliasByManagerInput){
    CreateAliasByManager(input:$input){
      message
    }
  }

 mutation LogAliasNoProduct($alias:String!){
    LogAliasNoProduct(alias:$alias){
      message
    }
  }



  
