  query GetUnAliasedReceipt ($input: GetRejectionReasonsInput!) {
    GetUnAliasedReceipt(input: $input) {
      images{
      uri
    }
    retailer{
      name
      _id
    }
    prediction

    }
  }
